runtime: nodejs18

env_variables:
  BOT_TOKEN: "OTgyNDk1NDMyMzgwOTE1NzUy.G_X0W9.Rpyjv8m5e6GBoqkLIU5pr3UtKcGACK9-kQnbIQ"
  MONGO_USERNAME: "DiscordBotUser"
  MONGO_PASSWORD: "SBaTjjZtmJF2tC72"
  BOT_ENV: "DEV"
  VAL_API_KEY: "HDEV-0d7a307a-ee7d-45bb-a94b-2542477677f1"
