name: Build Image and Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - dasam-discord-bot-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to docker user group
        run: |
          echo $USER
          newgrp docker

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dasam-discord-bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/dasam-discord-bot:latest

      - name: Setup environment variables in .env file
        run: |
          echo "BOT_ENV=${{ secrets.BOT_ENV }}" > ~/.env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> ~/.env
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> ~/.env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> ~/.env
          echo "VAL_API_KEY=${{ secrets.VAL_API_KEY }}" >> ~/.env

      - name: Deploy Docker container to Raspberry Pi
        run: |
          docker stop dasam-discord-bot || true
          docker rm dasam-discord-bot || true
          docker run -d \
            --name dasam-discord-bot \
            --env-file ~/.env \
            -p 3000:3000 \
            ${{ secrets.DOCKER_USERNAME }}/dasam-discord-bot:latest
